
[
	    {
	  "Name":"WARNING",
	  "Info":"Do not torrent",
	  "Payload":{
		  "Proxy":{
			  "Custom":false,
			  "Remote":"",
			  "Port":""
		  },
		  "Url":"e0c2d6ca5cdade5cc4c25ce6dcd2cccc5ce0c25ccec2cede",
		  "Host":true,
		  "Online-Host":true,
		  "Forward-Host":true,
		  "Reverse-Proxy":false,
		  "Keep-Alive":true
	  }
	  },
  {
	  "Name":"GTM-GS-GOWATCH-or-GS-PROMO",
	  "Info":"Send GS10-GS50 to 8080",
	  "Payload":{
		  "Proxy":{
			  "Custom":false,
			  "Remote":"",
			  "Port":""
		  },
		  "Url":"e6eae0e0dee4e85cf2deeae8eac4ca5cc6deda5ce6ce",
		  "Host":true,
		  "Online-Host":true,
		  "Forward-Host":true,
		  "Reverse-Proxy":false,
		  "Keep-Alive":true
	  }
  },
  
  {
	  "Name":"SMART-ALLOUT-PROMO",
	  "Info":"Register to Any ALLOUT Promos send to 9999",
	   "Payload":{
		  "Proxy":{
			  "Custom":false,
			  "Remote":"",
			  "Port":""
		  },
		  "Url":"eeeeee5ccededeced8caecd2c8cade5cc6deda5ce6ce",
		  "Host":true,
		  "Online-Host":true,
		  "Forward-Host":true,
		  "Reverse-Proxy":false,
		  "Keep-Alive":true
	  }
  },
  {
	  "Name":"TNT-ML--PROMO",
	  "Info":"ML10 send to 4545",
	   "Payload":{
		  "Proxy":{
			  "Custom":false,
			  "Remote":"",
			  "Port":""
		  },
		  "Url":"d0d6ce606ee664705ad2dc5acc62685c62ca6260605cdccae8",
		  "Host":true,
		  "Online-Host":true,
		  "Forward-Host":true,
		  "Reverse-Proxy":false,
		  "Keep-Alive":true
	  }
  },
  
    {
	  "Name":"TNT-IG-PROMO-NOT-WORKING",
	  "Info":"IG10 send to 4545",
	   "Payload":{
		  "Proxy":{
			  "Custom":false,
			  "Remote":"",
			  "Port":""
		  },
		  "Url":"d0d6ce606ee664705ad2dc5acc62685c62ca6260605cdccae8",
		  "Host":true,
		  "Online-Host":true,
		  "Forward-Host":true,
		  "Reverse-Proxy":false,
		  "Keep-Alive":true
	  }
  },
    {
	  "Name":"TNT-COC-PROMO-NOT-WORKING",
	  "Info":"COC10 send to 4545",
	   "Payload":{
		  "Proxy":{
			  "Custom":false,
			  "Remote":"",
			  "Port":""
		  },
		  "Url":"d0d6ce606ee664705ad2dc5acc62685c62ca6260605cdccae8",
		  "Host":true,
		  "Online-Host":true,
		  "Forward-Host":true,
		  "Reverse-Proxy":false,
		  "Keep-Alive":true
	  }
  },
    {
	  "Name":"TNT-FB-PROMO",
	  "Info":"FB10 send to 4545",
	   "Payload":{
		  "Proxy":{
			  "Custom":false,
			  "Remote":"",
			  "Port":""
		  },
		  "Url":"d0d6ce606ee664705ad2dc5acc62685c62ca6260605cdccae8",
		  "Host":true,
		  "Online-Host":true,
		  "Forward-Host":true,
		  "Reverse-Proxy":false,
		  "Keep-Alive":true
	  }
  },
  {
	  "Name":"SUN-TU50-PROMO",
	  "Info":"Send TU50-TU300 to 247",
	   "Payload":{
		  "Proxy":{
			  "Custom":false,
			  "Remote":"",
			  "Port":""
		  },
		  "Url":"e6cac6eae4ca5cecd2c4cae45cc6deda",
		  "Host":true,
		  "Online-Host":false,
		  "Forward-Host":false,
		  "Reverse-Proxy":false,
		  "Keep-Alive":false
	  }
  },
    {
	  "Name":"SUN-TU20-PROMO-NOT-WORKING",
	  "Info":"Send TU20 to 247",
	   "Payload":{
		  "Proxy":{
			  "Custom":false,
			  "Remote":"",
			  "Port":""
		  },
		  "Url":"eeeeee5ccededeced8caecd2c8cade5cc6deda",
		  "Host":true,
		  "Online-Host":true,
		  "Forward-Host":true,
		  "Reverse-Proxy":false,
		  "Keep-Alive":true
	  }
  }
]
